# Project information
site_name: Foxy Docs
site_description: Foxy Documentation
site_author: felixbrucker
site_url: https://docs.foxypool.io

# Repository
repo_name: foxy-docs
repo_url: https://github.com/felixbrucker/foxy-docs

# Theme
theme:
  name: 'material'
  favicon: assets/img/favicon.ico
  logo: assets/img/fox.png
  features:
    - navigation.tabs
  palette:
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github-alt

# Options
extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/felixbrucker
    - icon: fontawesome/brands/discord
      link: https://discord.gg/gNHhn9y

# Page tree
nav:
  - General:
      - Home: index.md
      - Getting Started: general/getting-started.md
      - Glossary: general/glossary.md
      - Configuring Scavenger: general/configuring-scavenger.md
      - Installing Nodejs: general/installing-nodejs.md
      - Donate: general/donate.md
  - Foxy-Pool:
      - Home: foxy-pool/index.md
      - Mining: foxy-pool/mining.md
      - Binding:
          - BHD: foxy-pool/binding/bhd.md
          - BURST: foxy-pool/binding/burst.md
          - HDD: foxy-pool/binding/hdd.md
          - LHD: foxy-pool/binding/lhd.md
          - XHD: foxy-pool/binding/xhd.md
      - EC:  foxy-pool/ec.md
      - Pledging: foxy-pool/pledging.md
      - Settings: foxy-pool/settings.md
      - Daily Rewards: foxy-pool/daily-rewards.md
      - Distribution Ratio: foxy-pool/distribution-ratio.md
      - API:
          - Overview: foxy-pool/api/overview.md
          - Web-UI API: foxy-pool/api/web-ui-api.md
          - Mining API: foxy-pool/api/mining-api.md
  - Foxy-Miner:
      - Home: foxy-miner/index.md
      - Installing: foxy-miner/installing.md
      - Configuration: foxy-miner/configuration.md
  - Foxy-Proxy:
      - Home: foxy-proxy/index.md
      - Installing: foxy-proxy/installing.md
      - Configuration: foxy-proxy/configuration.md
  - Pledge-Agent:
      - Home: pledge-agent/index.md
      - Supported coins: pledge-agent/supported-coins.md
      - Installing: pledge-agent/installing.md
      - Configuration: pledge-agent/configuration.md


# Extensions
markdown_extensions:
  - meta
  - attr_list
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
